language: ruby
cache: bundler

rvm:
  - 2.1.2

script: 'bundle exec rake test'

notifications:
  email:
    recipients:
      - apagano@wawand.co
    on_failure: change
    on_success: never
addons:
  code_climate:
    repo_token: c55d85a239cccfc962610effd319b2bc1e831a59c36fc1b267297d00d988bd09
